"""add attendance

Revision ID: 0b515c4b5f6d
Revises: e5bbeac6df5a
Create Date: 2026-08-30 18:50:03.753390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b515c4b5f6d'
down_revision: Union[str, Sequence[str], None] = 'e5bbeac6df5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('checked_in_date', sa.Date(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'timetable_id', 'checked_in_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
