"""update user information to be NON NULLABLE

Revision ID: 2ff32e152cde
Revises: 8178ca68b654
Create Date: 2026-09-01 10:08:44.734417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy 


# revision identifiers, used by Alembic.
revision: str = '2ff32e152cde'
down_revision: Union[str, Sequence[str], None] = '8178ca68b654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'face_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               nullable=False)
    op.alter_column('users', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('users', 'face_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               nullable=True)
    # ### end Alembic commands ###
