"""on-delete casacde registered if professor deletes timetable

Revision ID: 66b07d084b74
Revises: 538e54708dd6
Create Date: 2026-09-03 09:44:19.340754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b07d084b74'
down_revision: Union[str, Sequence[str], None] = '538e54708dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('registered_timetable_id_fkey'), 'registered', type_='foreignkey')
    op.create_foreign_key('registered_timetable_id_fkey', 'registered', 'timetables', ['timetable_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('registered_timetable_id_fkey', 'registered', type_='foreignkey')
    op.create_foreign_key(op.f('registered_timetable_id_fkey'), 'registered', 'timetables', ['timetable_id'], ['id'])
    # ### end Alembic commands ###
