"""Initial tables

Revision ID: 80cbf5839b23
Revises:
Create Date: 2026-09-13 13:25:04.830109

"""

from collections.abc import Sequence

import geoalchemy2
import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80cbf5839b23"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "rooms",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "role", sa.Enum("STUDENT", "STAFF", name="user_role"), nullable=False
        ),
        sa.Column(
            "gender", sa.Enum("MALE", "FEMALE", name="user_gender"), nullable=False
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "iom_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=True
        ),
        sa.Column("last_image_update", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "timetables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=100), nullable=False),
        sa.Column("start", sa.Time(), nullable=False),
        sa.Column("end", sa.Time(), nullable=False),
        sa.Column(
            "day_of_week",
            sa.Enum(
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                name="day_of_week",
            ),
            nullable=False,
        ),
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name="timetables_room_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"], ["users.id"], name="timetables_staff_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attendance",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("timetable_id", sa.Integer(), nullable=False),
        sa.Column("checked_in_date", sa.Date(), nullable=False),
        sa.Column("checked_in_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["timetable_id"], ["timetables.id"], name="attendance_timetable_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="attendance_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("user_id", "timetable_id", "checked_in_date"),
    )
    op.create_table(
        "registered",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("timetable_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["timetable_id"], ["timetables.id"], name="registered_timetable_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="registered_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("user_id", "timetable_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("registered")
    op.drop_table("attendance")
    op.drop_table("timetables")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("rooms")
    # ### end Alembic commands ###
